name: funcamp R Icarius API CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: V1
          gzip: false
          files: data/
          body: "Release of icaRius game"
