name: funcamp R Icarius API CI

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: build package
        run: cd data && 7za a -tzip ../icarius.solarus .
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: icarius.solarus