name: funcamp R Icarius API CI

on:
  push:
    branches:
      - gha2
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build package
        run: cd data && 7za a -tzip ../icarius.solarus .
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../icarius.solarus
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
